### ISSUE TITLE
[Request] Support for Windows Desktop

### ISSUE THREAD

**Issue by Heiland** [ajinasokan/flutter_displaymode#13]
Would be very appreciated if you could add support for higher refresh rates on Desktop as well.
Unfortunately at least on Windows the refresh rate of Flutter applications is limited to 60 Hz.

Thank you very much in advance

**Comment by ajinasokan** [comment]
@Heiland are you sure about this? From my understanding on Desktop, operating system doesn't set app's refresh rates. It is actually a monitor/display setting that you have to change in the settings. In mobile it is different because the display is capable of changing the refresh rate quickly and apps consume the entire display real estate. If Flutter app is not using the same refresh rate as monitor then it is Flutter framework that locks it, not Windows.

I would like to know more about this. What is the refresh rate of your monitor? Have you changed the refresh rate from the display settings to maximum? How you came to conclusion that Flutter app is running at 60Hz?

**Comment by Heiland** [comment]
The monitor is set to 160 Hz on Windows.
When I run the same Flutter application with an animation as a Desktop-version and compare this animation with the Web-version, I can clearly see that on the Web-version the animation is as smooth as one would expect it to be on 160 Hz while the Desktop-version is not as smooth - resembling the 60 Hz locked framerate.

There is an issue on the Flutter project regarding this topic:
[Desktop app frame rate isn't synced to display #49757](https://github.com/flutter/flutter/issues/49757#)

As per the linked issue 
[increase windows timer resolution and wire up basic vsync callback #27764](https://github.com/flutter/engine/pull/27764#issuecomment-888530823)
they were not able to determine the currently running refresh rate of DWM for UWP-applications and thus they kept the refresh rate locked to 60 Hz for Windows Desktop.

I hoped I could set the refresh rate of Desktop-applications manually using your Flutter-package and thus I would ask if it could be possible for you to add support for Windows Desktop like you did for Android.

**Comment by ajinasokan** [comment]
From everything I read it looks like this is not something a library can do. Instead need a modification in the engine itself. I will keep this issue open to keep track of new findings.

**Comment by Heiland** [comment]
Thank you very much for taking your time looking into this.

**Comment by AlexV525** [comment]
The original issue seems solved on Windows. The issue should be safe to close.
